node("docker") {
    docker.withRegistry('https://192.168.99.100:2376','3644bcbb-ab8d-4cc4-9912-f1096161394c') {
    
        git url: "https://github.com/umang-santuka/pocProject.git"'
    
        sh "git rev-parse HEAD > .git/commit-id"
        def commit_id = readFile('.git/commit-id').trim()
        println commit_id
    
        stage "build"
        def app = docker.build "app"
    
        stage "publish"
        app.push 'master'
        app.push "${commit_id}"
    }
}